# Generated by Django 6.0.5 on 2026-05-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_phoneotp_fuelrequest_payment_reference_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
